---
- name: Register Coffer in Keystone
  ansible.builtin.import_tasks: register.yml

- name: Configure Coffer
  ansible.builtin.import_tasks: config.yml

- name: Check Coffer containers
  ansible.builtin.import_tasks: check-containers.yml

- name: Bootstrap the Coffer database schema
  ansible.builtin.import_tasks: bootstrap.yml

- name: Flush Coffer handlers after successful bootstrap
  ansible.builtin.meta: flush_handlers
