---
- name: Register Coffer service, endpoints, and service user in Keystone
  ansible.builtin.import_role:
    name: service-ks-register
  vars:
    service_ks_register_auth: "{{ openstack_coffer_auth }}"
    service_ks_register_services: "{{ coffer_ks_services }}"
    service_ks_register_users: "{{ coffer_ks_users }}"
    service_ks_register_roles: "{{ coffer_ks_roles }}"
  no_log: true
