#!/usr/bin/env bash

set -euo pipefail

barbican_env="/etc/coffer-rgw/barbican.env"
s3_env="/etc/coffer-rgw/distribution.env"
python_helper="/tmp/guest-verify-rgw-kms.py"

test "$(id -u)" -eq 0
test -f "${barbican_env}"
test -f "${s3_env}"
test -f "${python_helper}"
test "$(stat -c '%a' "${barbican_env}")" = 600
test "$(stat -c '%a' "${s3_env}")" = 600

# Both files are owner-only runtime state generated by the lab harnesses.
# shellcheck disable=SC1090
source "${barbican_env}"
# shellcheck disable=SC1090
source "${s3_env}"
export COFFER_KMS_KEY_ID
export REGISTRY_STORAGE_S3_ACCESSKEY REGISTRY_STORAGE_S3_SECRETKEY

python3 "${python_helper}"
unset COFFER_KMS_USER_PASSWORD COFFER_KMS_KEY_ID
unset REGISTRY_STORAGE_S3_ACCESSKEY REGISTRY_STORAGE_S3_SECRETKEY
