[DEFAULT]
namespace = localhost
image_name_prefix = coffer-production-
tag = 2026.1-candidate

[coffer]
type = local
location = $locals_base

[coffer-user]
uid = 53002
gid = 53002

[registry-user]
uid = 53003
gid = 53003
