[DEFAULT]
namespace = localhost
image_name_prefix = coffer-ui-
tag = 2026.1-native-candidate

[horizon]
type = local
location = $locals_base/work/horizon-25.7.3

[skyline-console]
type = local
location = $locals_base/work/skyline-console-2026.1
